CACHE_DIR: ''
OUTPUT: 'output_test_tip.csv'

DATA:
    ROOT: '/Users/fege/Documents/school/tbad-8/'
    TRAIN_FILE: 'datasets_splits/TBAD-8/train.txt'
    TEST_FILE: 'datasets_splits/TBAD-8/test_reordered_part1.txt'
    DATASET: TBAD-8
    NUM_FRAMES: 8
    NUM_CLASSES: 8
    LABEL_LIST: 'labels/TBAD-8_labels.csv'
    SHOTS: 8
MODEL:
    ARCH: ViT-L/14@336px
    YOLO: 'Yolo-model/yolov8n.pt'
    IF_TEACHER: 1
    ZS: 0
    LABEL_SMOOTH: 1
    TEMPORAL_POOLING: 'fsattention'
    LP: 1
    ADAPTER_FUSE_TYPE: 2
TRAIN:
    BATCH_SIZE: 8 # BS 64
    ACCUMULATION_STEPS: 2
    EPOCHS: 15
    LR: 0.001
TEXT_PROMPT:
    N_CTX_PRE: 8
    CTX_PRE_INIT: "x x x x x x x x"
    N_CTX_POST: 3
    CTX_POST_INIT: "x x x"
